version: '3.2'

services:
  core:
    build:
      context: .
      dockerfile: ./docker/core/Dockerfile
    volumes:
      - ./app/:/app
    environment:
      - TZ=Asia/Tokyo
    logging:
      driver: json-file
      options:
        max-file: '1'
        max-size: 1m
    restart: always
    tty: true
    ports:
      - "4000:4000"
