name: Build and Push Core Image

on:
  push:
    branches:
      - "develop"
      - "feature/*"

jobs:
  build-and-publish:
    name: Build and Push docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup Google Cloud
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: kameds-f228e

    - name: Configure docker for artifact registry
      run: |
        gcloud auth configure-docker us-west1-docker.pkg.dev

    - name: set TAG
      run: |
        echo "TAG=$(echo $GITHUB_REF | awk -F/ '{print $NF}')" >> $GITHUB_ENV

    - name: Build
      run: |
        docker build -t us-west1-docker.pkg.dev/kameds-f228e/test-repo/ss-core:${{ env.TAG }} -f deploy/core/Dockerfile .

    - name: Push
      run: |
        docker push us-west1-docker.pkg.dev/kameds-f228e/test-repo/ss-core:${{ env.TAG }}